"""add ticketing domain models

Revision ID: 556ad47db59e
Revises: 0001_initial
Create Date: 2026-10-03 10:54:24.472287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '556ad47db59e'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

USER_ROLE = postgresql.ENUM(
    "OWNER", "MANAGER", "AGENT", name="user_role", create_type=False
)
TICKET_STATUS = postgresql.ENUM(
    "OPEN",
    "ASSIGNED",
    "IN_PROGRESS",
    "RESOLVED",
    "CLOSED",
    name="ticket_status",
    create_type=False,
)
TICKET_PRIORITY = postgresql.ENUM(
    "LOW", "NORMAL", "HIGH", "URGENT", name="ticket_priority", create_type=False
)
TICKET_EVENT_TYPE = postgresql.ENUM(
    "CREATED",
    "STATUS_CHANGED",
    "ASSIGNMENT_CHANGED",
    "PRIORITY_CHANGED",
    "CATEGORY_CHANGED",
    "COMMENT_ADDED",
    name="ticket_event_type",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    for enum in (USER_ROLE, TICKET_STATUS, TICKET_PRIORITY, TICKET_EVENT_TYPE):
        enum.create(bind, checkfirst=True)

    op.create_table('companies',
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('api_keys',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('key_hash', sa.String(
                        length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('last_used_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('revoked_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'key_hash',
                                        name='uq_api_keys_company_hash')
                    )
    op.create_table('customers',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=True),
                    sa.Column('external_reference', sa.String(
                        length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'external_reference',
                                        name='uq_customers_company_external_reference')
                    )
    op.create_table('users',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=255), nullable=False),
                    sa.Column('role', USER_ROLE, nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'email',
                                        name='uq_users_company_email')
                    )
    op.create_table('tickets',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('public_id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', TICKET_STATUS, nullable=False),
                    sa.Column('priority', TICKET_PRIORITY, nullable=False),
                    sa.Column('category', sa.String(
                        length=100), nullable=True),
                    sa.Column('requester_id', sa.Uuid(), nullable=False),
                    sa.Column('assignee_id', sa.Uuid(), nullable=True),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['assignee_id'], ['users.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['requester_id'], ['customers.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'public_id',
                                        name='uq_tickets_company_public_id')
                    )
    op.create_table('comments',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('ticket_id', sa.Uuid(), nullable=False),
                    sa.Column('author_id', sa.Uuid(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('is_internal', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['author_id'], ['users.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('idempotency_keys',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=False),
                    sa.Column('request_hash', sa.String(
                        length=64), nullable=False),
                    sa.Column('response_status', sa.Integer(), nullable=False),
                    sa.Column('response_body', sa.JSON(), nullable=False),
                    sa.Column('ticket_id', sa.Uuid(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'key',
                                        name='uq_idempotency_company_key')
                    )
    op.create_table('ticket_events',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('ticket_id', sa.Uuid(), nullable=False),
                    sa.Column('actor_id', sa.Uuid(), nullable=True),
                    sa.Column('event_type', TICKET_EVENT_TYPE, nullable=False),
                    sa.Column('previous_value', sa.Text(), nullable=True),
                    sa.Column('new_value', sa.Text(), nullable=True),
                    sa.Column('occurred_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['actor_id'], ['users.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_events')
    op.drop_table('idempotency_keys')
    op.drop_table('comments')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('api_keys')
    op.drop_table('companies')
    bind = op.get_bind()
    for enum in (TICKET_EVENT_TYPE, TICKET_PRIORITY, TICKET_STATUS, USER_ROLE):
        enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
