"""add ticket query indexes

Revision ID: e4666b94ca1c
Revises: 556ad47db59e
Create Date: 2026-10-03 11:08:33.268507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e4666b94ca1c'
down_revision: Union[str, None] = '556ad47db59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tickets_company_assignee', 'tickets', ['company_id', 'assignee_id'], unique=False)
    op.create_index('ix_tickets_company_created_at', 'tickets', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_company_priority', 'tickets', ['company_id', 'priority'], unique=False)
    op.create_index('ix_tickets_company_requester', 'tickets', ['company_id', 'requester_id'], unique=False)
    op.create_index('ix_tickets_company_status', 'tickets', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_company_status', table_name='tickets')
    op.drop_index('ix_tickets_company_requester', table_name='tickets')
    op.drop_index('ix_tickets_company_priority', table_name='tickets')
    op.drop_index('ix_tickets_company_created_at', table_name='tickets')
    op.drop_index('ix_tickets_company_assignee', table_name='tickets')
    # ### end Alembic commands ###
